# Generated by Django 3.2.9 on 2021-11-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='nome',
            new_name='name',
        ),
    ]
