# Generated by Django 3.2.9 on 2021-11-06 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_nome_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 6, 18, 11, 14, 19765, tzinfo=utc)),
        ),
    ]
