# Generated by Django 3.2.9 on 2021-11-06 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 18, 14, 53, 397220, tzinfo=utc)),
        ),
    ]
