# Generated by Django 3.2.9 on 2021-11-06 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211106_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='posted',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 20, 4, 4, 52342, tzinfo=utc)),
        ),
    ]
